[[pass]]
host = "r740"
path = '~/projects/rocc_nvm'
cmd  = 'sudo ./scripts/nvm_server --host=localhost  --port=6666 -use_nvm=true -touch_mem=false --nvm_sz=10 --nvm_file=/dev/dax1.3'

[[pass]]
host = "val19"
path = '~/projects/rocc_nvm'
cmd  = './scripts/nvm_client -addr="r740:6666" --coros=8 --threads=20 --id=0 --use_nic_idx=1 --use_read=false --payload=64 --add_sync=true --address_space=2 --random=true'

###############################################################################################################################################
# [[pass]]                                                                                                                                    #
# host = "val22"                                                                                                                              #
# path = '~/projects/rocc_nvm'                                                                                                                #
# cmd  = './scripts/nvm_client -addr="r740:6666" --threads=10 --id=2 --use_nic_idx=1 --use_read=false --payload=8 --add_sync=false --coros=8' #
###############################################################################################################################################



###########################################################################################################
# [[pass]]                                                                                                #
# host = "val20"                                                                                          #
# path = ''                                                                                               #
# cmd  = './nvm_client -addr="r740:6666" --threads=24 --id=1 --use_nic_idx=1 --use_read=true --payload=8' #
###########################################################################################################


#########################################################################################
# [[pass]]                                                                              #
# host = "val19"                                                                        #
# path = '~/'                                                                           #
# cmd  = './nvm_aclient -addr="r740:6666" --threads=12 --id=0 --use_nic_idx=1'          #
#                                                                                       #
#                                                                                       #
# [[pass]]                                                                              #
# host = "r740"                                                                         #
# path = '~/projects/rocc_nvm'                                                          #
# cmd  = './scripts/nvm_aclient -addr="val19:6666" --threads=12 --id=0 --use_nic_idx=1' #
#########################################################################################


